EditorCameraInPlay: true
DoSimulatePhysics: true
RenderEntityInfo: true
RenderPhysicsShape: true
GizmoTransSpace: 1
TranslationSnapValue: 0.5
RotationSnapValue: 45
SceneFilePath: assets\scenes\AITestScene.pbsc