EditorCameraInPlay: true
DoSimulatePhysics: true
RenderEntityInfo: false
RenderPhysicsShape: true
GizmoTransSpace: 1
TranslationSnapValue: 0.5
RotationSnapValue: 45
SceneFilePath: assets\scenes\TestScene.pbsc