EditorCameraInPlay: false
DoSimulatePhysics: true
RenderEntityInfo: false
RenderPhysicsShape: true
GizmoTransSpace: 0
TranslationSnapValue: 0.5
RotationSnapValue: 45
SceneFilePath: assets\scenes\RotationSphere.pbsc